name: CI

on:
  push:
    branches:
    - main
    paths:
    - templates/*
  workflow_dispatch:

jobs:
  qemu:
    name: Qcow2 Image build
    runs-on: self-hosted
    env:
      CENTOS_VERSION: "7.9"
      CENTOS_RELEASE: "2009"
    steps:
      - name: checkout master
        uses: actions/checkout@master
      - name: Run Packer build
        env:
          HYPERVISOR: qemu
          PACKER_LOG: "yes"
        run: |
          cd templates
          rm /opt/data/packer/OUTPUT_DIR/CentOS-7-x86_64-${CENTOS_RELEASE} /opt/data/packer/OUTPUT_DIR/CentOS-7-x86_64-${CENTOS_RELEASE}/CentOS-7-x86_64-${CENTOS_RELEASE}.qcow2
          packer build centos-${HYPERVISOR}-${CENTOS_VERSION}-x86_64-${CENTOS_RELEASE}.json
          qemu-img convert -p -c /opt/data/packer/OUTPUT_DIR/CentOS-7-x86_64-${CENTOS_RELEASE}/CentOS-7-x86_64-${CENTOS_RELEASE} -O qcow2 /opt/data/packer/OUTPUT_DIR/CentOS-7-x86_64-${CENTOS_RELEASE}/CentOS-7-x86_64-${CENTOS_RELEASE}.qcow2
          cp /opt/data/packer/OUTPUT_DIR/CentOS-7-x86_64-${CENTOS_RELEASE}/CentOS-7-x86_64-${CENTOS_RELEASE}.qcow2 /opt/users/saratkumar.k/Packer/centos
          rm /opt/data/packer/OUTPUT_DIR/CentOS-7-x86_64-${CENTOS_RELEASE} /opt/data/packer/OUTPUT_DIR/CentOS-7-x86_64-${CENTOS_RELEASE}/CentOS-7-x86_64-${CENTOS_RELEASE}.qcow2
          echo "Centos image of type ${HYPERVISOR} version ${CENTOS_VERSION} release ${CENTOS_RELEASE} available @ http://10.46.8.152/Users/saratkumar.k/Packer/centos/"
  vmware-iso:
    name: Ova Image build
    needs: qemu
    runs-on: self-hosted
    env:
      CENTOS_VERSION: "7.9"
      CENTOS_RELEASE: "2009"
    steps:
      - name: checkout master
        uses: actions/checkout@master
      - name: Run Packer build
        env:
          HYPERVISOR: vmware-iso
          ESXI_HOST: ${{ secrets.ESXI_HOST }}
          ESXI_USERNAME: ${{ secrets.ESXI_USERNAME }}
          ESXI_PASSWORD: ${{ secrets.ESXI_PASSWORD }}
          ESXI_DATASTORE: ${{ secrets.ESXI_DATASTORE }}
          PACKER_LOG: "yes"
        run: |
          cd templates
          rm /opt/data/packer/OUTPUT_DIR/CentOS-7-x86_64-${CENTOS_RELEASE}/CentOS-7-x86_64-${CENTOS_RELEASE}.ova
          packer build centos-${HYPERVISOR}-${CENTOS_VERSION}-x86_64-${CENTOS_RELEASE}.json
          cp /opt/data/packer/OUTPUT_DIR/CentOS-7-x86_64-${CENTOS_RELEASE}/CentOS-7-x86_64-${CENTOS_RELEASE}.ova /opt/users/saratkumar.k/Packer/centos
          rm /opt/data/packer/OUTPUT_DIR/CentOS-7-x86_64-${CENTOS_RELEASE}/CentOS-7-x86_64-${CENTOS_RELEASE}.ova
          echo "Centos image of type ${HYPERVISOR} version ${CENTOS_VERSION} release ${CENTOS_RELEASE} available @ http://10.46.8.152/Users/saratkumar.k/Packer/centos/"
