name: CI

on:
  push:
    branches:
    - main
    paths:
    - templates/*
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        hypervisor: [qemu, vmware-iso]
    runs-on: self-hosted
    env:
      CENTOS_VERSION: "7.9"
      CENTOS_RELEASE: "2009"
    steps:
      - name: checkout master
        uses: actions/checkout@master
      - name: Run Packer build
        env:
          HYPERVISOR: ${{ matrix.hypervisor }}
          PACKER_LOG: "yes"
        run: |
          packer build templates/centos-${HYPERVISOR}-${CENTOS_VERSION}-x86_64-${CENTOS_RELEASE}.json
          qemu-img convert -c /opt/data/packer/OUTPUT_DIR/CentOS-7-x86_64-${CENTOS_RELEASE} -O qcow2 /opt/data/packer/OUTPUT_DIR/CentOS-7-x86_64-${CENTOS_RELEASE}.qcow2
          cp /opt/data/packer/OUTPUT_DIR/CentOS-7-x86_64-${CENTOS_RELEASE}.qcow2 /opt/users/saratkumar/Packer/centos
