name: Centos Image build

on:
  push:
    branches:
    - main
    paths:
    - templates/*
  workflow_dispatch:

jobs:
  clean-up:
    name: Cleanup artifact directory
    runs-on: self-hosted
    env:
      OUTPUT_DIR: "/opt/data/packer/OUTPUT_DIR"
    steps:
      - name: Run cleanup
        run: |
          rm -rf ${OUTPUT_DIR}/CentOS*
  build:
    name: Packer Image build
    needs: clean-up
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        hypervisor: [qemu, vmware-iso]
        release: [7.9.2009]
    env:
      OUTPUT_DIR: "/opt/data/packer/OUTPUT_DIR"
      FILER_PATH: "/opt/users/saratkumar.k/Packer/centos"
      ESXI_HOST: ${{ secrets.ESXI_HOST }}
      ESXI_USERNAME: ${{ secrets.ESXI_USERNAME }}
      ESXI_PASSWORD: ${{ secrets.ESXI_PASSWORD }}
      ESXI_DATASTORE: ${{ secrets.ESXI_DATASTORE }}
    steps:
      - name: checkout master
        uses: actions/checkout@master
      - name: Run Packer build
        env:
          HYPERVISOR: ${{ matrix.hypervisor }}
          RELEASE_VERSION: ${{ matrix.release }}
        run: |
          cd templates
          packer build centos-${HYPERVISOR}-${RELEASE_VERSION}-x86_64.json
          if [[ "${HYPERVISOR}" == "qemu" ]]; then
            qemu-img convert -p -c ${OUTPUT_DIR}/CentOS-7-x86_64-${RELEASE_VERSION}/CentOS-7-x86_64-${RELEASE_VERSION} -O qcow2 ${OUTPUT_DIR}/CentOS-7-x86_64-${RELEASE_VERSION}/CentOS-7-x86_64-${RELEASE_VERSION}.qcow2
            cp ${OUTPUT_DIR}/CentOS-7-x86_64-${RELEASE_VERSION}/CentOS-7-x86_64-${RELEASE_VERSION}.qcow2 ${FILER_PATH}
          elif [[ "${HYPERVISOR}" == "vmware-iso" ]]; then
            cp ${OUTPUT_DIR}/CentOS-7-x86_64-${RELEASE_VERSION}/CentOS-7-x86_64-${RELEASE_VERSION}.ova ${FILER_PATH}
          fi
          chmod +r ${FILER_PATH}/*
          echo "Centos image of type ${HYPERVISOR} version ${CENTOS_VERSION} release ${RELEASE_VERSION} available @ http://10.46.8.152/Users/saratkumar.k/Packer/centos/"