name: Centos Image build

on:
  workflow_dispatch:

jobs:
  qemu:
    name: Image build
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        hypervisor: [qemu, vmware-iso]
        release: [7.8.2003, 7.9.2009]
    steps:
      - name: checkout master
        uses: actions/checkout@master
      - name: Run Packer build
        env:
          HYPERVISOR: ${{ matrix.hypervisor }}
          RELEASE_VERSION: ${{ matrix.release }}
          PACKER_LOG: "yes"
        run: |
          cd templates
          echo "building centos-${HYPERVISOR}-${RELEASE_VERSION}-x86_64.json"
          ls centos-${HYPERVISOR}-${RELEASE_VERSION}-x86_64.json
